"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

s = 0
arr = []
def fibo(a, b):
    if b > 4000000:
        return 
    arr.append(b)
    fibo(b, b + a)
    return 
fibo(1,2)
for i in arr:
    if i%2 == 0:
        s+=i
print(s)